## LOAD NUMPY

In [2]:
import numpy as np

### The Basics

In [3]:
a=np.array([1,3,4,7])
print(a)

[1 3 4 7]


In [6]:
b=np.array([[6,7,8], [3,1,7]])
print(b)

[[6 7 8]
 [3 1 7]]


### Dimensions

In [14]:
a.ndim

1

In [16]:
b.ndim

2

### Shape

In [17]:
a.shape

(4,)

In [18]:
b.shape

(2, 3)

### Type

In [19]:
a.dtype

dtype('int64')

In [20]:
b.dtype

dtype('int64')

In [22]:
c=np.array([1,3,4,7], dtype='int16')
c.dtype

dtype('int16')

### Size 

In [23]:
# size tells the number of columns or fields in the array
a.size

4

In [24]:
b.size

6

In [25]:
c.size

4

In [29]:
# item size tells the memory bytes the array takes.
a.itemsize

8

In [27]:
b.itemsize

8

In [28]:
c.itemsize

2

In [30]:
# get total size 
a.size*a.itemsize

32

In [31]:
# another simple way 
a.nbytes

32

In [32]:
b.nbytes

48

In [33]:
c.nbytes

8

### Accessing/Changing specific Rows, Columns, Elements etc

In [36]:
a=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [37]:
# Access specific Row[r,c]
a[0,:]

array([1, 2, 3, 4, 5])

In [38]:
# Access Specif Column
a[:, 2]

array([3, 8])

In [40]:
# Access in between rows
a[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [42]:
# Jump in between rows
a[:,1:4:2]

array([[2, 4],
       [7, 9]])

In [44]:
# Change specific element
a[1,3]=15
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8 15 10]]


In [46]:
# Change all elements in a specific column 
a[:,3]=15
print(a)

[[ 1  2  3 15  5]
 [ 6  7  8 15 10]]


### 3D Arrays

In [47]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
# Get Specific Element
a[0,1,0]

np.int64(3)

In [52]:
# Replace
a[:,1,:]=[[33,33],[88,88]]
print(a)

[[[ 1  2]
  [33 33]]

 [[ 5  6]
  [88 88]]]


### Initializing Different Types of Arrays

In [59]:
# 1D array
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [58]:
# 2D Array
np.zeros((5,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [61]:
# 3D array
np.zeros((2,3,3), dtype='int')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [63]:
# 4D array
np.zeros((2,3,2,5), dtype='int')

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]])

In [64]:
np.ones((4,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [65]:
np.full((2,2),11)

array([[11, 11],
       [11, 11]])

In [70]:
# will call the last variable 'a'
np.full(a.shape,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [71]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [72]:
#Random Decimal Elements
np.random.rand(4,2)

array([[0.8085317 , 0.54715249],
       [0.80316105, 0.41777367],
       [0.45330655, 0.89232397],
       [0.06181915, 0.94222738]])

In [76]:
# Random Integer Elements between 5 to 10
np.random.randint(5,10,size=(3,3))

array([[7, 9, 9],
       [5, 6, 5],
       [5, 9, 6]], dtype=int32)

In [78]:
# Identity Matrix (Square Matrix)
np.identity(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [81]:
#Repeat an array horizontally 
arr=np.array([1,2,3])
r=np.repeat(arr,3,axis=0)
print(r)

[1 1 1 2 2 2 3 3 3]


In [84]:
# Repeat an arrray vertically
arr=np.array([[1,2,3]])
r=np.repeat(arr,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [89]:
# Solution
o=np.ones((5,5),dtype='int')
z=np.zeros((3,3))
z[1,1]=9
o[1:-1,1:-1]=z
print(o)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### Copying Array

In [93]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [94]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [95]:
a+2

array([3, 4, 5, 6])

In [96]:
a-2

array([-1,  0,  1,  2])

In [97]:
a**2

array([ 1,  4,  9, 16])

In [98]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [99]:
b=np.array([1,0,1,0])
b

array([1, 0, 1, 0])

In [100]:
a+b

array([2, 2, 4, 4])

In [101]:
# Try Trignometry
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [102]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [103]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

### Some Basic Linear Algebra

In [105]:
# Matrix Multiplication
a=np.ones((2,3), dtype='int')
b=np.full((3,2),2)
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [106]:
# Find Determinant
c=np.identity(5)
np.linalg.det(c)

np.float64(1.0)

### Statistics

In [118]:
stats=np.array([[1,2,9,4],[5,6,7,8]])
stats

array([[1, 2, 9, 4],
       [5, 6, 7, 8]])

In [119]:
np.min(stats)

np.int64(1)

In [121]:
np.min(stats, axis=0)

array([1, 2, 7, 4])

In [122]:
np.min(stats, axis=1)

array([1, 5])

In [123]:
np.max(stats)

np.int64(9)

In [124]:
np.max(stats,axis=0)

array([5, 6, 9, 8])

In [125]:
np.max(stats,axis=1)

array([9, 8])

In [126]:
np.sum(stats)

np.int64(42)

In [127]:
np.sum(stats,axis=0)

array([ 6,  8, 16, 12])

In [128]:
np.sum(stats,axis=1)

array([16, 26])

### Reorganizing Arrays

In [129]:
before=np.array([[1,2,9,4],[5,6,7,8]])
after=before.reshape(4,2)  # Reshape to 2D Array
after

array([[1, 2],
       [9, 4],
       [5, 6],
       [7, 8]])

In [131]:
after=before.reshape(2,2,2)  # Reshape to 3D Array
after

array([[[1, 2],
        [9, 4]],

       [[5, 6],
        [7, 8]]])

In [132]:
# Vertiacl Stacking of Arrays
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.vstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [133]:
np.vstack([a,b,a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [135]:
# Horizontal Stacking of Arrays
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Load Data From File

In [146]:
file = np.genfromtxt('C:/Users/fahad/Desktop/data.txt', delimiter=',')
filedata=file.astype('int32')
filedata

array([[  1,   2,   4,  55,  77,   1,   2,  44,   2,   9],
       [  3,   5,   6,  88,  43,   5,  12, 543,   1,   3],
       [ 11,  44,  99,  32,   2,  77,  31,  23,   7,   8]], dtype=int32)

### Boolean Masking and Advanced Indexing

In [147]:
filedata>50

array([[False, False, False,  True,  True, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False,  True, False,
        False],
       [False, False,  True, False, False,  True, False, False, False,
        False]])

In [149]:
filedata[filedata>50]

array([ 55,  77,  88, 543,  99,  77], dtype=int32)

In [150]:
np.any(filedata>50,axis=0)

array([False, False,  True,  True,  True,  True, False,  True, False,
       False])

In [151]:
((filedata>50)&(filedata<100))

array([[False, False, False,  True,  True, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [False, False,  True, False, False,  True, False, False, False,
        False]])

In [152]:
(~((filedata>50)&(filedata<100)))

array([[ True,  True,  True, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True, False,  True,  True,  True,
         True]])